NetCoreMVC4/Models/ErrorViewModel.cs
namespace NetCoreMVC4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetCoreMVC4/Models/Kitap.cs
namespace NetCoreMVC4.Models
{
    public class Kitap
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Yazar { get; set; }
        public string Kategori { get; set; }
        public string YayınEvi { get; set; }
    }
}

NetCoreMVC4/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreMVC4.Models;
using System.Diagnostics;

namespace NetCoreMVC4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NetCoreMVC4/Controllers/KitapController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreMVC4.Models;

namespace NetCoreMVC4.Controllers
{
    public class KitapController : Controller
    {
        public IActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Kitap kitap)
        {

            return Content("urun basariyla eklendi");
        }

        public IActionResult Guncelle()
        {
            return View();
        }
        public IActionResult Sil()
        {
            return View();
        }

        public IActionResult Index()
        {
            Kitap kitap = new Kitap();
            kitap.Id = 1;
            kitap.Ad = "A'dan Z'ye Siber Guvenlik";
            kitap.Yazar = "A. Can POLAT";
            kitap.Kategori = "Bilgisayar";
            kitap.YayınEvi = "Kodlab";

            Kitap kitap2 = new Kitap();
            kitap2.Id = 2;
            kitap2.Ad = "A'dan Z'ye Siber Guvenlik 2";
            kitap2.Yazar = "A. Polat Can";
            kitap2.Kategori = "Pc";
            kitap2.YayınEvi = "KodLab 2";

            Kitap kitap3 = new Kitap();
            kitap3.Id = 3;
            kitap3.Ad = "A'dan Z'ye Siber Guvenlik 3";
            kitap3.Yazar = "D. Can Polat";
            kitap3.Kategori = "IOS";
            kitap3.YayınEvi = "Kodlab 3";

            List <Kitap> kitaplar = new List <Kitap> ();
            kitaplar.Add (kitap);
            kitaplar.Add(kitap2);
            kitaplar.Add(kitap3);

            return View(kitaplar);
        }

    }
}

NetCoreMVC4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NetCoreMVC4/Views/Kitap/Ekle.cshtml
<h3>Kitap Ekleme Sayfası</h3>

<form action="/Kitap/Ekle" method="post">
    <label for="Ad">Ad</label>
    <input type="text" name="Ad" />
    <label for="Stok">Stok</label>
    <input type="text" name="Stok" />

    <button>Kaydet</button>
</form>

NetCoreMVC4/Views/Kitap/Index.cshtml
@model List<Kitap>

<a type="button" class="btn btn-primary" asp-area="" asp-controller="Kitap" asp-action="Ekle">Ekle</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Ad</th>
            <th scope="col">Yazar</th>
            <th scope="col">Kategori</th>
            <th scope="col">Yayın Evi</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Kitap kitaplar in Model)
        {
        <tr>
            <td>@kitaplar.Id</td>
            <td>@kitaplar.Ad</td>
            <td>@kitaplar.Yazar</td>
            <td>@kitaplar.Kategori</td>
            <td>@kitaplar.YayınEvi</td>
            <td>
                    
                    <a type="button" class="btn btn-info" asp-area="" asp-controller="Kitap" asp-action="Index">Güncelle</a>
                    <a type="button" class="btn btn-danger" asp-area="" asp-controller="Kitap" asp-action="Index">Sil</a>
            </td>

        </tr>
        }
    </tbody>
</table>

NetCoreMVC4/Views/Kitap/Sil.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

NetCoreMVC4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreMVC4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetCoreMVC4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetCoreMVC4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kitap" asp-action="Index">Kitaplar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NetCoreMVC4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>